### ISSUE TITLE
tinyfpgab doesn't work with Python 3

### ISSUE THREAD

**Issue by afiskon** [tinyfpga/TinyFPGA-B-Series#13]
Considering that Python 2 will be officially deprecated in 2020 it's worth considering to make tinyfpgab compatible with Python 3.

**Comment by Obijuan** [comment]
We are migrating icestudio and Apio to python3. Everything has been already migrated except the tinyFPGA programmer. It would be great to achieve it.

I will do it, and test it.  If @tinyfpga agree, the first task is to create a branch (let's call it python3 for example). Then I will pull-req the migration to that branch so that we all can test it. Is it ok for you, Luke?

**Comment by tinyfpga** [comment]
That would be great.  I agree that Python 3 is the way to go.  If you move tinyfpgab to Python 3 and its tested I will merge it in.  Thanks!

**Comment by Obijuan** [comment]
There you have an initial pull request. I am waiting for your commands on how to proceed. As you like

**Comment by Jesus89** [comment]
Hi @tinyfpga.

Could you create and upload a new release for the programmer (`1.1.0`) with the latest changes (Python2 and Python3 support)?

Then, we could close finally this ticket :wink:

Thanks.

**Comment by tinyfpga** [comment]
Ok @Jesus89 and @Obijuan, it took too long, but tinyfpgab v1.1.0 with Python 3 support is released on pypi.

**Comment by Jesus89** [comment]
Thanks Luke!
